### ISSUE TITLE
Re-write Software Supply Chain Use case document

### ISSUE THREAD

**Issue by kkarunakaran89** [ietf-scitt/draft-birkholz-scitt-software-supply-chain-use-cases#6]
Per IETF115, we need to rewrite our use case document to be compliant with IETF format. Opening this issue to track progress on the doc so we can discuss it at IETF SCITT working group meeting when we're ready. 
@yogeshbdeshpande 

Reference use case: https://datatracker.ietf.org/doc/html/[draft-ietf-ace-usecases-05](https://datatracker.ietf.org/doc/html/draft-ietf-ace-usecases-05)

**Comment by yogeshbdeshpande** [comment]
We are working on this task:

Here are my comments on the document!
(Please note that I will make these comments on github also).

General Comment:
We need to harmonize the format so that the shape and style of description of each use case looks similar. 

Specific Comments:

Use Case 1: Trust Bond between Package Supplier and the Signing Authority

(a)	Missing bits: Needs to map the problem with real use case in hand? The use case starts more with a problem rather than describing a proper industry use case.
(b)	Remove the usage of word Trust and Trustworthiness but use lack of information on aspects that can be assertively verified by the end user, so that the trust factor is “implicitly”  established.

Use Case 2: Scalable Determination of Trustworthiness in Multi-Stakeholder Ecosystems
(a)	Title is very mis-leading: There is no scalability again in Trustworthiness. There is incremental mechanism of further deeper verification that grows the trust.
(b)	Need to re-write the title taking specific industry and its use case built into it.
(c)	Again need to highlight a real use case and then come to the problem what the use case exposes.

Use Case 4:  This use case is not clear to me at all??  Specifically, the comment:
 Over time, there has been an increasing amount of providers of the same version of the software component source over the Internet  How can the same version of the software component source is produced by multiple vendors ?
Need to re-write the use case completely.

Use Case 5: Checking the History of Statements about Software by Auditors
Again, Better to demonstrate a real world example use case rather than jumping into the problem domain.

**Comment by yogeshbdeshpande** [comment]
The document re-write with new format, style and harmonization effort is now complete!

All the changes have been merged!
